# Default values for poem-generator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: hocikto19/poem-generator
  pullPolicy: Always
  tag: "latest"

service:
  type: LoadBalancer
  port: 80

autoscaling:
  enabled: false
ingress:
  enabled: false
imagePullSecrets: []
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
